### ISSUE TITLE
Issue with set_diffuse_texture_from_file Function in SAPIEN 3.0.0b1

### ISSUE THREAD

**Issue by chanmi2** [haosulab/SAPIEN#176]
**System:**
 - OS version: Ubuntu 20.04
 - Python version: Python 3.9
 - SAPIEN version: 3.0.0b1 
 - Environment: Desktop

**Describe the bug**
The "set_diffuse_texture_from_file" function, which worked fine in SAPIEN 2.2.2, no longer seems to exist in SAPIEN 3.0.0b1. Running the example code results in the following error:
AttributeError: 'sapien.pysapien.render.RenderMaterial' object has no attribute 'set_diffuse_texture_from_file'

**To Reproduce**
Steps to reproduce the behavior (use pastebin for code):
1.  Create a material object using renderer.create_material()
2. Try setting a texture with material.set_diffuse_texture_from_file("/path/to/texture.jpg")
ex)
import sapien.core as sapien
engine = sapien.Engine()
renderer = sapien.SapienRenderer()
scene = engine.create_scene()
scene.set_renderer(renderer)
material = renderer.create_material()
material.set_diffuse_texture_from_file("/path/to/texture.jpg")  # This line causes the error

**Expected behavior**
In SAPIEN 2.2.2, this function successfully set the diffuse texture for a material. I expect the function to work similarly in SAPIEN 3.0.0b1, or if the function has changed, documentation on the new usage should be provided.

**Screenshots**
N/A

**Additional context**
I have upgraded from SAPIEN 2.2.2 to SAPIEN 3.0.0b1 to use ManiSkill3. However I could not find any documentation about changes to this function in the newer version. I am trying to find a way to apply textures to objects using custom files. Please provide information on any similar functions or alternative methods available in the new version.

**Comment by BeLl0o** [comment]
I'm encountering the same issue after upgrading to SAPIEN 3.0.0b1, and I was wondering if you have found a solution or any alternative way to set a texture from file?
Would really appreciate it if you could share any insights. Thanks a lot!
